### ISSUE TITLE
请教下add_context一般在什么情况下会比较有效？

### ISSUE THREAD

**Issue by clw5180** [tascj/kaggle-kuzushiji-recognition#3]
就是single_level.py里面的global_context，非常感谢！

**Comment by tascj** [comment]
我只知道在这个比赛数据上没影响，没删掉只是没时间重新训练。

**Comment by clw5180** [comment]
> 我只知道在这个比赛数据上没影响，没删掉只是没时间重新训练。

一般是对小目标比较有效么？还是对需要附近信息的目标比较有效
